export const CLASS_NAMES = {
  0: 'potted plant',
  1: 'tv',
  2: 'chair',
  3: 'person',
  4: 'microwave',
  5: 'refrigerator',
  6: 'book',
  7: 'clock',
  8: 'vase',
  9: 'dining table',
  10: 'bed',
  11: 'stop sign',
  12: 'truck',
  13: 'car',
  14: 'teddy bear',
  15: 'tennis racket',
  16: 'handbag',
  17: 'backpack',
  18: 'bird',
  19: 'boat',
  20: 'cell phone',
  21: 'train',
  22: 'sandwich',
  23: 'bowl',
  24: 'cat',
  25: 'keyboard',
  26: 'airplane',
  27: 'zebra',
  28: 'bus',
  29: 'tie',
  30: 'traffic light',
  31: 'apple',
  32: 'baseball bat',
  33: 'knife',
  34: 'cake',
  35: 'wine glass',
  36: 'cup',
  37: 'surfboard',
  38: 'spoon',
  39: 'skis',
  40: 'banana',
  41: 'donut',
  42: 'bottle',
  43: 'sink',
  44: 'toilet',
  45: 'broccoli',
  46: 'skateboard',
  47: 'couch',
  48: 'remote',
  49: 'laptop',
  50: 'scissors',
  51: 'bicycle'
};

export function getClassLabel(id) {
  const key = typeof id === 'number' ? id : Number(id);
  return CLASS_NAMES[key] ?? `class ${id}`;
}

